apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inveniordm
  namespace: argocd
spec:
  project: invenio-project
  sources:
    - repoURL: https://github.com/lpandath/inveniordm-helm-values.git
      targetRevision: feature/vault-integration-restructure
      ref: values
    - repoURL: https://inveniosoftware.github.io/helm-invenio/
      chart: invenio
      targetRevision: "0.8.1"
      helm:
        valueFiles:
        - $values/inveniordm/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: invenio

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
